import { useState } from 'react';
import API from '../services/api';
import CrudPage from '../components/CrudPage';
import AIAnalysisDisplay from '../components/AIAnalysisDisplay';

const columns = [
  { key: 'id', label: 'ID' },
  { key: 'title', label: 'Title' },
  { key: 'reportType', label: 'Type' },
  { key: 'Patient.firstName', label: 'Patient', render: (i) => i.Patient ? `${i.Patient.firstName} ${i.Patient.lastName}` : 'Clinic-wide' },
  { key: 'generatedBy', label: 'Generated By' },
  { key: 'status', label: 'Status' },
  { key: 'createdAt', label: 'Date', render: (i) => new Date(i.createdAt).toLocaleDateString() },
];

const detailFields = [
  { key: 'id', label: 'Report ID' },
  { key: 'title', label: 'Title' },
  { key: 'reportType', label: 'Report Type' },
  { key: 'patientId', label: 'Patient ID' },
  { key: 'generatedBy', label: 'Generated By' },
  { key: 'status', label: 'Status' },
];

const formFields = [
  { key: 'title', label: 'Title', required: true },
  { key: 'reportType', label: 'Report Type', type: 'select', options: ['cycle-summary', 'embryo-ranking', 'clinic-performance', 'patient-prognosis', 'lab-quality'] },
  { key: 'patientId', label: 'Patient ID (optional)', type: 'number' },
  { key: 'content', label: 'Content', type: 'textarea' },
  { key: 'status', label: 'Status', type: 'select', options: ['draft', 'final', 'reviewed'] },
];

function AIReportsPage() {
  const [generating, setGenerating] = useState(false);
  const [genResult, setGenResult] = useState('');
  const [genType, setGenType] = useState('clinic-performance');
  const [genPatientId, setGenPatientId] = useState('');

  const generateReport = async () => {
    setGenerating(true);
    setGenResult('');
    try {
      const { data } = await API.post('/ai-reports/generate', { reportType: genType, patientId: genPatientId || null });
      setGenResult(data.aiAnalysis);
    } catch (err) {
      setGenResult('Failed: ' + (err.response?.data?.error || err.message));
    } finally {
      setGenerating(false);
    }
  };

  return (
    <div>
      <div style={{ background: 'var(--bg-card)', border: '1px solid var(--border)', borderRadius: 12, padding: 24, marginBottom: 24 }}>
        <h3 style={{ marginBottom: 16, fontSize: 16, fontWeight: 700 }}>Generate AI Report</h3>
        <div style={{ display: 'flex', gap: 12, alignItems: 'flex-end', flexWrap: 'wrap' }}>
          <div className="form-group" style={{ marginBottom: 0, flex: 1, minWidth: 200 }}>
            <label>Report Type</label>
            <select className="form-control" value={genType} onChange={e => setGenType(e.target.value)}>
              <option value="cycle-summary">Cycle Summary</option>
              <option value="embryo-ranking">Embryo Ranking</option>
              <option value="clinic-performance">Clinic Performance</option>
              <option value="patient-prognosis">Patient Prognosis</option>
              <option value="lab-quality">Lab Quality</option>
            </select>
          </div>
          <div className="form-group" style={{ marginBottom: 0, width: 150 }}>
            <label>Patient ID (opt)</label>
            <input type="number" className="form-control" value={genPatientId} onChange={e => setGenPatientId(e.target.value)} placeholder="Optional" />
          </div>
          <button className="btn btn-info" onClick={generateReport} disabled={generating} style={{ height: 42 }}>
            {generating ? 'Generating...' : 'Generate Report'}
          </button>
        </div>
        {genResult && <AIAnalysisDisplay content={genResult} title={`AI ${genType.replace(/-/g, ' ').replace(/\b\w/g, l => l.toUpperCase())} Report`} />}
      </div>
      <CrudPage title="AI Reports" endpoint="/ai-reports" columns={columns} formFields={formFields} detailFields={detailFields} />
    </div>
  );
}

export default AIReportsPage;
